#  Computational Geophysics (CF234104)
## Solving System of Linear Equation iteratively : Gauss-Seidel Method
## $$Ax=b$$

In [1]:
import numpy as np

### input matrix A,b, and initial guess x0

In [2]:
A= np.array([[12,-2,3,1],
             [-2,15,6,-3],
             [1,6,20,-4],
             [0,-3,2,9]],dtype=float)

b=np.array([0,0,20,0],dtype=float).reshape(-1,1)
x0=np.array([0,0,0,0],dtype=float).reshape(-1,1)

print('\nA = \n',A)
print('\nb = \n',b)
print('\nx0 = \n',x0)



A = 
 [[12. -2.  3.  1.]
 [-2. 15.  6. -3.]
 [ 1.  6. 20. -4.]
 [ 0. -3.  2.  9.]]

b = 
 [[ 0.]
 [ 0.]
 [20.]
 [ 0.]]

x0 = 
 [[0.]
 [0.]
 [0.]
 [0.]]


### decomposing matrix A into D, L, U

In [3]:
D=np.diag(np.diag(A))
L=-np.tril(A,-1)
U=-np.triu(A,1)

print('\nD = \n',D)
print('\nL = \n',L)
print('\nU = \n',U)


D = 
 [[12.  0.  0.  0.]
 [ 0. 15.  0.  0.]
 [ 0.  0. 20.  0.]
 [ 0.  0.  0.  9.]]

L = 
 [[-0. -0. -0. -0.]
 [ 2. -0. -0. -0.]
 [-1. -6. -0. -0.]
 [-0.  3. -2. -0.]]

U = 
 [[-0.  2. -3. -1.]
 [-0. -0. -6.  3.]
 [-0. -0. -0.  4.]
 [-0. -0. -0. -0.]]


### Calculating Tgs, cgs

#### $Tgs=(D-L)^{-1}U$
#### $cgs=(D-L)^{-1}b$


In [7]:
inv_DL=np.linalg.inv(D-L)
Tgs= inv_DL @ U
cgs= inv_DL @ b

print("Tgs =\n", Tgs)
print("cgs =\n", cgs)

Tgs =
 [[ 0.          0.16666667 -0.25       -0.08333333]
 [ 0.          0.02222222 -0.43333333  0.18888889]
 [ 0.         -0.015       0.1425      0.1475    ]
 [ 0.          0.01074074 -0.17611111  0.03018519]]
cgs =
 [[ 0.        ]
 [ 0.        ]
 [ 1.        ]
 [-0.22222222]]


### Gauss-seidel
#### solution of x :
#### $x_{update}=Tgs * x+cgs$

In [9]:
#set the iteration
maxit=100
tol=1e-5


x=x0
print("iter   x1      x2      x3      x4      Errors")

for i in range(1,maxit+1):
    x_update=Tgs@x + cgs
    Err=np.linalg.norm(x_update-x,ord=1) #using L1 norm
    
    print(f"{i:3d}  {x_update[0, 0]:5.4f}  {x_update[1, 0]:5.4f} {x_update[2, 0]:5.4f}  {x_update[3, 0]:5.4f} {Err:11.5f}")#display vector x each iteration
    
    
    if Err<tol: #check convergence
          break
          
    x=x_update
          
x_sol=np.round(x,4)


print("\nSolution of x =\n", x_sol)

iter   x1      x2      x3      x4      Errors
  1  0.0000  0.0000 1.0000  -0.2222     1.22222
  2  -0.2315  -0.4753 1.1097  -0.4050     0.99933
  3  -0.3229  -0.5679 1.1055  -0.4350     0.21820
  4  -0.3348  -0.5738 1.1019  -0.4361     0.02257
  5  -0.3348  -0.5726 1.1013  -0.4356     0.00238
  6  -0.3345  -0.5722 1.1013  -0.4355     0.00086
  7  -0.3344  -0.5722 1.1013  -0.4355     0.00013
  8  -0.3344  -0.5722 1.1013  -0.4355     0.00001

Solution of x =
 [[-0.3344]
 [-0.5722]
 [ 1.1013]
 [-0.4355]]
