# Computational Geophysics (CF234104)
## Solving System of Linear Equation : Gauss Elimination
## $$Ax=b$$

### Program for solving system of Linear equation Ax=b
### input : matrix A dan vector b
### output: solution of vector x 

In [13]:
import numpy as np

### input

In [45]:
A=np.array([[1,3,6],[2,-1,1],[4,-2,3]],dtype=float)
b=np.array([19,-2,-1],dtype=float)
print('A =',A)
print('b=',b)

A = [[ 1.  3.  6.]
 [ 2. -1.  1.]
 [ 4. -2.  3.]]
b= [19. -2. -1.]


### Making an augmented matrix

In [56]:
Ab=np.column_stack((A, b))
m=len(A)
print('Ab=',Ab)
print('m=',m)

Ab= [[ 1.  3.  6. 19.]
 [ 2. -1.  1. -2.]
 [ 4. -2.  3. -1.]]
m= 3


### Gauss Elimination process : 1.) forward elimination phase

In [57]:
for i in range (m-1):
    for j in range (i+1,m):
        eps=Ab[j,i]/Ab[i,i]
        Ab[j,i:]=Ab[j,i:]-eps*Ab[i,i:]
    
print('Ab= ',Ab)



Ab=  [[  1.   3.   6.  19.]
 [  0.  -7. -11. -40.]
 [  0.   0.   1.   3.]]


### Gauss Elimination process : 2.) backward-subtitution phase

In [55]:
x=np.zeros(m)

for i in range(m-1, -1, -1):
    x[i] = (Ab[i, -1] - np.dot(Ab[i, i+1:m], x[i+1:m])) / Ab[i, i]

print('Solution x = ', x)

Solution x =  [-2.  1.  3.]
