# Computational Geophysics (CF234104)
## Solving System of Linear Equation : Gauss-Jordan Elimination
## $$Ax=b$$

![](Gaus-jordan.png)

### Program for solving system of Linear equation Ax=b
### input : matrix A dan vector b
### output: solution of vector x 

In [69]:
import numpy as np

### input

In [70]:
A=np.array([[1,3,6],[2,-1,1],[4,-2,3]], dtype=float)
b=np.array([19,-2,-1],dtype=float)
print('A =',A)
print('b=',b)

A = [[ 1.  3.  6.]
 [ 2. -1.  1.]
 [ 4. -2.  3.]]
b= [19. -2. -1.]


### making an augmented matrix [A,b]

In [79]:
Ab= np.column_stack((A, b))
m=len(A)
print('Ab=',Ab)
print('m=',m)

Ab= [[ 1.  3.  6. 19.]
 [ 2. -1.  1. -2.]
 [ 4. -2.  3. -1.]]
m= 3


#### Gaus-Jordan elimination process

In [76]:
for i in range(m):
    Ab[i,:]=Ab[i,:]/Ab[i,i] #setting all diagonal component = 1
    
    for j in range(m):
        if i !=j:
            Ab[j,:]=Ab[j,:]-Ab[i,:]*Ab[j,i] #setting other elements to zero
            
            
#solution is the last column of modified augmented matrix Ab
print('Ab=',Ab)
x=Ab[:,-1]
print('Solution of x =',x)

Ab= [[ 1.  0.  0. -2.]
 [-0.  1.  0.  1.]
 [ 0.  0.  1.  3.]]
Solution of x = [-2.  1.  3.]


#### Verification

In [77]:
print('b=',np.dot(A,x))

b= [19. -2. -1.]


### using while loops

In [78]:
i=0
while i<m:
    Ab[i,:]=Ab[i,:]/Ab[i,i] #setting all diagonal component = 1
    
    j=0
    while j<m:
          if i !=j:
            Ab[j,:]=Ab[j,:]-Ab[i,:]*Ab[j,i] #setting other elements to zero
          j=j+1
        
    i=i+1
            
            
#solution is the last column of modified augmented matrix Ab
print('Ab=',Ab)
x=Ab[:,-1]
print('Solution of x =',x)
    

Ab= [[ 1.  0.  0. -2.]
 [ 0.  1.  0.  1.]
 [ 0.  0.  1.  3.]]
Solution of x = [-2.  1.  3.]
