#  Computational Geophysics (CF234104)
## Solving System of Linear Equation iteratively : Jacobi Method
## $$Ax=b$$

In [75]:
import numpy as np

#### input matrix A,b, and initial guess x0

In [76]:
A= np.array([[12,-2,3,1],
             [-2,15,6,-3],
             [1,6,20,-4],
             [0,-3,2,9]],dtype=float)

b=np.array([0,0,20,0],dtype=float).reshape(-1,1)
x0=np.array([0,0,0,0],dtype=float).reshape(-1,1)

print('\nA = \n',A)
print('\nb = \n',b)
print('\nx0 = \n',x0)



A = 
 [[12. -2.  3.  1.]
 [-2. 15.  6. -3.]
 [ 1.  6. 20. -4.]
 [ 0. -3.  2.  9.]]

b = 
 [[ 0.]
 [ 0.]
 [20.]
 [ 0.]]

x0 = 
 [[0.]
 [0.]
 [0.]
 [0.]]


### decomposing matrix A into D, L, U

In [77]:
D=np.diag(np.diag(A))
L=-np.tril(A,-1)
U=-np.triu(A,1)

print('\nD = \n',D)
print('\nL = \n',L)
print('\nU = \n',U)


D = 
 [[12.  0.  0.  0.]
 [ 0. 15.  0.  0.]
 [ 0.  0. 20.  0.]
 [ 0.  0.  0.  9.]]

L = 
 [[-0. -0. -0. -0.]
 [ 2. -0. -0. -0.]
 [-1. -6. -0. -0.]
 [-0.  3. -2. -0.]]

U = 
 [[-0.  2. -3. -1.]
 [-0. -0. -6.  3.]
 [-0. -0. -0.  4.]
 [-0. -0. -0. -0.]]


### Calculate T & c


#### $T=D^{-1}(L+U)$
#### $c=D^{-1}b$

In [78]:
D_inv=np.linalg.inv(D)
T=D_inv @ (L+U)
c=D_inv@b

print('\nT = \n',T)
print('\nc = \n',c)


T = 
 [[ 0.          0.16666667 -0.25       -0.08333333]
 [ 0.13333333  0.         -0.4         0.2       ]
 [-0.05       -0.3         0.          0.2       ]
 [ 0.          0.33333333 -0.22222222  0.        ]]

c = 
 [[0.]
 [0.]
 [1.]
 [0.]]


## Jacobi iteration

#### solution of x :
### $x_{update}=Tx+c$

In [85]:
maxit=100
tol=1e-5


x=x0
print("iter   x1      x2      x3      x4      Errors")

for i in range(1,maxit+1):
    x_update=T@x + c
    Err=np.linalg.norm(x_update-x,ord=1) #using L1 norm
    
    print(f"{i:3d}  {x_update[0, 0]:5.4f}  {x_update[1, 0]:5.4f} {x_update[2, 0]:5.4f}  {x_update[3, 0]:5.4f} {Err:11.5f}")#display vector x each iteration
    
    
    if Err<tol: #check convergence
          break
          
    x=x_update
          
x_sol=np.round(x,4)


print("\nSolution of x =\n", x_sol)
       

iter   x1      x2      x3      x4      Errors
  1  0.0000  0.0000 1.0000  0.0000     1.00000
  2  -0.2500  -0.4000 1.0000  -0.2222     0.87222
  3  -0.2981  -0.4778 1.0881  -0.3556     0.34731
  4  -0.3220  -0.5461 1.0871  -0.4010     0.13859
  5  -0.3294  -0.5580 1.0997  -0.4236     0.05442
  6  -0.3326  -0.5685 1.0991  -0.4304     0.02112
  7  -0.3337  -0.5701 1.1011  -0.4338     0.00796
  8  -0.3341  -0.5717 1.1010  -0.4347     0.00319
  9  -0.3343  -0.5719 1.1013  -0.4352     0.00115
 10  -0.3344  -0.5721 1.1012  -0.4354     0.00048
 11  -0.3344  -0.5721 1.1013  -0.4354     0.00017
 12  -0.3344  -0.5722 1.1013  -0.4354     0.00007
 13  -0.3344  -0.5722 1.1013  -0.4355     0.00002
 14  -0.3344  -0.5722 1.1013  -0.4355     0.00001
 15  -0.3344  -0.5722 1.1013  -0.4355     0.00000

Solution of x =
 [[-0.3344]
 [-0.5722]
 [ 1.1013]
 [-0.4355]]


In [80]:
b


array([[ 0.],
       [ 0.],
       [20.],
       [ 0.]])

In [81]:
b=np.dot(A,x_sol)
print('b=',np.round(b))

b= [[ 0.]
 [ 0.]
 [20.]
 [-0.]]
