### Pengantar Python

In [46]:
print('Hello guys, perkenalkan')
print('Nama saya .......')
print('NRP 12345678')
print('Saya siap belajar pemrograman dengan Python')

Hello guys, perkenalkan
Nama saya .......
NRP 12345678
Saya siap belajar pemrograman dengan Python


## Importing library Numpy

In [47]:
import numpy as np

### Create an array from a Python list

In [48]:

x= np.array([1, 2, 3])
print('x=',x)



x= [1 2 3]


### Create an array filled with zeros

In [59]:
xzero=np.zeros((10,10))
print('xz=',xzero)

xz= [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Create an array filled with ones

In [60]:
xone=np.ones((5, 5))
print('xone = ', xone)

xone =  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Create an array with a range of values

In [64]:
xarr=np.arange(21)
print('xarr = ',xarr)

xarr =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### Matrix Operation

In [67]:
A=np.array([[1,2,3],
           [2,-1,3],
           [1,0,2]])
print("A= ",A)

B=np.array([[1,1,1],[-2,1,0],[1,-1,-1]])
print("B= ",A)

print('A+B = ',A+B)
print('A-B=',A-B)
C=A*B
print('C = ',C)

Atrans=np.transpose(A)
Ainv=np.linalg.inv(A)
print('Atrans = ', Atrans)
print('Ainv = ', Ainv)

A=  [[ 1  2  3]
 [ 2 -1  3]
 [ 1  0  2]]
B=  [[ 1  2  3]
 [ 2 -1  3]
 [ 1  0  2]]
A+B =  [[ 2  3  4]
 [ 0  0  3]
 [ 2 -1  1]]
A-B= [[ 0  1  2]
 [ 4 -2  3]
 [ 0  1  3]]
C =  [[ 1  2  3]
 [-4 -1  0]
 [ 1  0 -2]]
Atrans =  [[ 1  2  1]
 [ 2 -1  0]
 [ 3  3  2]]
Ainv =  [[ 2.  4. -9.]
 [ 1.  1. -3.]
 [-1. -2.  5.]]


In [ ]:
#indexing matriks
A1=A[:,1]
print('Baris satu matriks A=',A1)

A_kolom2=A[0,1]
print('Kolom dua matriks A=',A_kolom2)

C=np.ones((3,3))
print('C = ',C)

In [ ]:
A.shape

### Basic Indexing (1D Array):

- Zero-based indexing: The first element is at index 0, the second at index 1, and so on.
- Negative indexing: -1 refers to the last element, -2 refers to the second-last, and so on

In [70]:
arr = np.array([10, 20, 30, 40, 50])
print('arr =',arr)
print(arr[0])  # Access first element (10)
print(arr[2])  # Access third element (30)
print(arr[-1]) # Access last element (50)
arr.shape

arr = [10 20 30 40 50]
10
30
50


(5,)

### Indexing a 2D Array (Matrix)
- The first index specifies the row and the second index specifies the column.

In [73]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('matrix =',matrix)
print(matrix[0, 0])  # First row, first column (1)
print(matrix[1, 2])  # Second row, third column (6)
print(matrix[-1, -1]) # Last row, last column (9)
matrix.shape

matrix = [[1 2 3]
 [4 5 6]
 [7 8 9]]
1
6
9


(3, 3)

### Slicing an Array

In [79]:
#for 1D array
arr = np.array([10, 20, 30, 40, 50])
print('arr=',arr)
print(arr[1:4])  # Slices from index 1 to 3 (output: [20, 30, 40])
print(arr[:3])   # Slices from start to index 2 (output: [10, 20, 30])
print(arr[2:])   # Slices from index 2 to the end (output: [30, 40, 50])


arr= [10 20 30 40 50]
[20 30 40]
[10 20 30]
[30 40 50]


In [85]:
#for 2D arrays
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice the first two rows and all columns
print(matrix[:2, :])  # Output: [[1, 2, 3], [4, 5, 6]]

# Slice the last two columns of all rows
print(matrix[:, 1:])  # Output: [[2, 3], [5, 6], [8, 9]]

# Slice specific elements: second row, first two columns
print(matrix[1, :2])  # Output: [4, 5]

matrix[0:3,0:2]

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]
[4 5]


array([[1, 2],
       [4, 5]])